### ISSUE TITLE
Unable to run dev container on aarch64 host

### ISSUE THREAD

**Issue by dustinblack** [Elektrobit/ebcl_template#15]
Trying to run the SDK dev container on my Linux aarch64 host environment I consistently get this failure state:

```
[3153 ms] Start: Run in container: '/home/ebcl/.vscode-server/bin/dc96b837cf6bb4af9cd736aa3af08cf8279f7685/bin/helpers/check-requirements.sh'
[3379 ms] 
[3379 ms] 
[3692 ms] 
[3693 ms] qemu-x86_64-static: QEMU internal SIGSEGV {code=MAPERR, addr=0x20}
Segmentation fault (core dumped)
qemu-x86_64-static: QEMU internal SIGSEGV {code=MAPERR, addr=0x20}
Segmentation fault (core dumped)
[3693 ms] Exit code 139
[3699 ms] Command in container failed: '/home/ebcl/.vscode-server/bin/dc96b837cf6bb4af9cd736aa3af08cf8279f7685/bin/helpers/check-requirements.sh'
[3699 ms] qemu-x86_64-static: QEMU internal SIGSEGV {code=MAPERR, addr=0x20}
Segmentation fault (core dumped)
qemu-x86_64-static: QEMU internal SIGSEGV {code=MAPERR, addr=0x20}
Segmentation fault (core dumped)
[3699 ms] Exit code 139
```

**Comment by thir820** [comment]
Hi @dustinblack,

thanks for your interest!
Unfortunately aarch64 host environments are not supported at the moment. I will come back to you when this changes.

Regards,
Thomas

**Comment by thir820** [comment]
Hi @dustinblack,

building on arm64 host is now possible. I tested with Ubuntu in a Raspberry Pi 5. The steps are:

1) Preprare the dev container:

- Clone https://github.com/Elektrobit/ebcl_dev_container
- Build the container for arm64 by running _builder/build_container_

2) Prepare the workspace:

- Clone https://github.com/Elektrobit/ebcl_template
- Run VS Code and open workspace from ebcl_sdk.code-workspace file
- Reopen in container

3) Build an arm64 image:

- Open the image folder, e.g. _/workspace/images/arm64/qemu/ebcl/crinit/debootstrap_
- Build the image and run it in QEMU by running `make` in this folder.

4) Cross-building

- On the host: Install binfmt support: `sudo apt install binfmt-support qemu qemu-user-static`
- In the container: Open the image folder, e.g. _/workspace/images/amd64/qemu/ebcl/crinit/debootstrap_
- Build the image and run it in QEMU by running `make` in this folder.
